apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmu-fe-host
  labels:
    app: rmu-fe-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmu-fe-host
  template:
    metadata:
      labels:
        app: rmu-fe-host
    spec:
      containers:
      - name: rmu-fe-host
        image: labcabrera/rmu-fe-host:latest
        ports:
        - containerPort: 8080
        env:

        - name: RMU_FE_HOST_PUBLIC_PATH
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_FE_HOST_PUBLIC_PATH

        - name: RMU_MODULE_FEDERATION_STRATEGIC
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_MODULE_FEDERATION_STRATEGIC

        - name: RMU_MODULE_FEDERATION_TACTICAL
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_MODULE_FEDERATION_TACTICAL

        - name: RMU_MODULE_FEDERATION_NPC
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_MODULE_FEDERATION_NPC
